### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by zevv** [liquid600pgm/nadio#1]
```
 ... /home/ico/external/nadio/src/nadio/gui.nim(7, 13) Error: cannot open file: rdgui/label
```

**Comment by liquidev** [comment]
Ah yes, this is what happens when you work on two projects at the same time and forget to push one before the other. Try reinstalling `rdgui` and compiling again.

**Comment by liquidev** [comment]
Oh, and keep in mind: this is highly WIP, it doesn't even make sound yet.

**Comment by zevv** [comment]
Quoting lqdev (2020-02-15 21:17:47)

> Oh, and keep in mind: this is highly WIP, it doesn't even make sound yet.

Oh I know. But I do have sound, but no gui yet :)

https://github.com/zevv/nimsynth

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by liquidev** [comment]
That's exactly why I have to create a plugin framework ;)

Resolved, closing.
